### ISSUE TITLE
Add definittion to DefinitelyTyped

### ISSUE THREAD

**Issue by komenank** [manuc66/react-cytoscapejs-typescript-sample#2]
Would you add your definition to DefinitelyTyped? This will make it installable using: 
`npm install @types/react-cytoscape`
See https://definitelytyped.org/guides/contributing.html for instructions.

**Comment by manuc66** [comment]
Hi,

Here is the attempt : https://github.com/DefinitelyTyped/DefinitelyTyped/pull/45577

**Comment by manuc66** [comment]
PR has been merged
